[build]
  publish = "public"
  # No necesitamos build command para archivos estáticos
  # command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects (se configurarán cuando tengamos el backend)
# [[redirects]]
#   from = "/api/*"
#   to = "https://tu-backend-url.com/api/:splat"
#   status = 200
#   force = true
